# 1
В стандартный поток вывода или в файл output.txt выведите 3
вещественных числа (медиану, среднее арифметическое и среднеквадратическое отклонение) с точностью 
2 знака после запятой, разделив их одним пробелом.

In [78]:
import numpy as np
with open('numpy.txt') as file:
    a = np.genfromtxt(file)
print("{:.2f}, {:.2f}, {:.2f}".format(np.median(a), np.mean(a), np.std(a)))

6104.00, 5442.20, 2612.10


# 2
В стандартный поток вывода или в файл output.txt необходимо вывести единственное число, равное номеру (не путайте номер с ИНДЕКСОМ) наиболее часто встречающегося цвета:

In [98]:
import numpy as np
with open('input.csv') as file:
    fashion = np.genfromtxt(file, delimiter=',')
column_sums = fashion.sum(axis=0).tolist()
print(column_sums.index(max(column_sums)) + 1)
# column_sums

1


# 3
В файле input.csv содержатся записи о подходах, сделанных клиентами за последние 
35 дней. Массив содержит N строк и 35 столбцов, где N — это количество спортсменов в клубе.
В стандартный поток вывода или в файл output.txt запишите единственное число 
1 или 2, в зависимости от Вашего решения. Если в клубе больше спортсменов, совершающих примерно одно и то же число подходов, запишите 1, иначе — запишите 2

In [21]:
import numpy as np
with open('input.csv') as file:
    a =  np.genfromtxt(file, delimiter=',')
std  = np.std(a, 1)
print(2 if ((std > 4).tolist().count(True) > (std > 4).tolist().count(False)) else 1)

1


# 5
 Вам дан csv-файл с количеством побед каждого из участников клуба (их 15) за каждый из 30 дней месяца. Присваиванием в срез замените значение в первой строке (конечно, эта строка принадлежит Гарри) на среднее значение побед по этому дню, умноженное на 
1.5.

In [54]:
import numpy as np
with open('input.csv') as file:
    a =  np.genfromtxt(file, delimiter=',')
a[0] = np.fix(a.mean(axis=0) * 1.5)
np.savetxt("output.csv", a, delimiter=',')

In [51]:
a

array([[40., 39., 37., 37., 35., 35., 38., 39., 39., 39., 32., 32., 33.,
        37., 36., 31., 36., 36., 35., 36., 33., 35., 41., 37., 33., 32.,
        36., 38., 35., 33., 38., 39., 33., 39., 40.],
       [21., 22., 32., 22., 34., 31., 25., 28., 29., 26., 20., 21., 31.,
        25., 34., 17., 27., 34., 16., 17., 19., 21., 17., 32., 23., 15.,
        21., 19., 26., 19., 18., 19., 18., 29., 33.],
       [30., 28., 20., 32., 21., 23., 29., 28., 24., 24., 19., 20., 29.,
        26., 28., 27., 17., 31., 18., 15., 15., 21., 22., 18., 22., 23.,
        25., 30., 28., 19., 19., 30., 18., 31., 17.],
       [26., 20., 27., 28., 17., 26., 21., 25., 23., 26., 19., 27., 17.,
        24., 30., 21., 24., 27., 20., 27., 21., 16., 23., 33., 31., 20.,
        18., 29., 30., 28., 22., 29., 16., 16., 17.],
       [32., 34., 30., 25., 30., 28., 21., 25., 22., 28., 15., 16., 16.,
        19., 17., 31., 30., 34., 34., 29., 23., 16., 34., 26., 19., 20.,
        33., 29., 23., 15., 32., 27., 15., 24., 26.],


In [39]:
np.fix(a.mean(axis=0) * 1.5)

array([40., 39., 37., 37., 35., 35., 38., 39., 39., 39., 32., 32., 33.,
       37., 36., 31., 36., 36., 35., 36., 33., 35., 41., 37., 33., 32.,
       36., 38., 35., 33., 38., 39., 33., 39., 40.])

In [27]:
b = 35.7
int(b)

35

In [23]:
a

array([[22., 28., 33., 17., 21., 33., 27., 34., 27., 31., 16., 16., 25.,
        34., 21., 17., 30., 21., 31., 20., 15., 19., 32., 23., 20., 16.,
        16., 23., 19., 21., 22., 31., 33., 30., 30.],
       [21., 22., 32., 22., 34., 31., 25., 28., 29., 26., 20., 21., 31.,
        25., 34., 17., 27., 34., 16., 17., 19., 21., 17., 32., 23., 15.,
        21., 19., 26., 19., 18., 19., 18., 29., 33.],
       [30., 28., 20., 32., 21., 23., 29., 28., 24., 24., 19., 20., 29.,
        26., 28., 27., 17., 31., 18., 15., 15., 21., 22., 18., 22., 23.,
        25., 30., 28., 19., 19., 30., 18., 31., 17.],
       [26., 20., 27., 28., 17., 26., 21., 25., 23., 26., 19., 27., 17.,
        24., 30., 21., 24., 27., 20., 27., 21., 16., 23., 33., 31., 20.,
        18., 29., 30., 28., 22., 29., 16., 16., 17.],
       [32., 34., 30., 25., 30., 28., 21., 25., 22., 28., 15., 16., 16.,
        19., 17., 31., 30., 34., 34., 29., 23., 16., 34., 26., 19., 20.,
        33., 29., 23., 15., 32., 27., 15., 24., 26.],
